name: Kata-Alejandro-API

on:
  push:
    branches:
      - main  # Ejecutar solo en la rama "main"

  schedule:
    - cron: "30 8 * * *"  # Se ejecuta todos los días a las 8:30 AM UTC

  workflow_dispatch:  # Permite ejecución manual en GitHub Actions

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 3  # Permite la ejecución de 3 pruebas en simultáneo
      matrix:
        test_class:
          - "org.bdb.kata.api.tests.GetApiTest"
          - "org.bdb.kata.api.tests.PostApiTest"
          - "org.bdb.kata.api.tests.PutApiTest"
          - "org.bdb.kata.api.tests.DeleteApiTest"

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verificar permisos del wrapper de Gradle
        run: chmod +x gradlew

      - name: Construir el proyecto (sin ejecutar tests)
        run: ./gradlew clean build -x test

      - name: Ejecutar pruebas de API con Serenity BDD
        run: ./gradlew clean test --tests ${{ matrix.test_class }}

      - name: Subir reportes de Serenity
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-reports
          path: target/site/serenity/
